name = "Ignored Files ###"
version = 1

[[gitignore.section]]
name = "Rust / Cargo"

[[gitignore.section.rule]]
ignore = ["/target", "bench-output.txt", "supply-chain/.cargo-vet/"]
note = "Rust / Cargo etc..."

[[gitignore.section]]
name = "Mise"

[[gitignore.section.rule]]
ignore = ["mise.local.lock", "mise.local.toml"]
note = "Mise Local"
