# SPDX-FileCopyrightText: 2026 Elio Severo Junior <elioseverojunior@gmail.com>
#
# SPDX-License-Identifier: MIT OR Apache-2.0

name: Mise

concurrency:
  group: mise-${{ github.ref_name }}
  cancel-in-progress: ${{ github.ref_name != github.event.repository.default_branch }}

on:
  pull_request:
    branches:
      - main
    paths:
      - "**/*.rs"
      - "**/Cargo.toml"
      - "**/Cargo.lock"
      - ".cargo/config.toml"
      - "rust-toolchain.toml"
      - "mise.toml"
      - "mise.lock"
      - ".github/workflows/mise.yml"
  push:
    branches:
      - main
    paths:
      - "**/*.rs"
      - "**/Cargo.toml"
      - "**/Cargo.lock"
      - ".cargo/config.toml"
      - "rust-toolchain.toml"
      - "mise.toml"
      - "mise.lock"
      - ".github/workflows/mise.yml"
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * 1"

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN || github.token }}
  MISE_TASK_RUN_AUTO_INSTALL: false

jobs:
  setup:
    name: Tool manifest installs
    runs-on: ${{ vars.RUNS_ON_ARM64 || vars.RUNS_ON || 'ubuntu-latest' }}
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: "recursive"
          fetch-depth: 0
          fetch-tags: "true"
          ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.ref }}
          token: ${{ secrets.GITHUB_TOKEN || github.token }}

      - uses: ./.github/actions/setup-rust-env
